### PR TITLE
Moving to at_core 8.x-3.1

### PR DESCRIPTION
**Pull request by Favenzio**
# What does this Pull Request do?

This pull request updates Carapace so that it uses the latest (as of August 2018) base theme provided by Adaptivetheme (8.x-3.1)

# What's new?

Carapace has been updated so that users can make more changes to the site's look and feel using the interface provided by the theme settings. These changes include:

- Additional Menu settings available using the Responsive Menus extension tab.
- Additional fonts available using the Fonts extension tab.
- Additional Touch Icons for mobile devices available using the Touch Icons extension tab.
- Additional Shortcodes available using the Shortcodes extension tab.
- Automated creation of Flexslider Slideshows using the Slideshows extension tab.
- Additional Regions available for display and configuration using the Layouts tab.
- Additional default color schemes using the Color Scheme tab. (Known issue: Some colors are not mapping to the correct regions.)

# How should this be tested?

Make sure you have the 8.x-3.1 of Adaptivetheme (https://www.drupal.org/project/adaptivetheme) version installed in your /themes folder. Also, make sure you have installed the 8.x-3.2 version of at_tools (https://www.drupal.org/project/at_tools) in your /modules folder. Clone or download this version of Carapace to /themes/custom and enable as you would enable any other theme. More info at: http://docs.adaptivethemes.com/

# Additional Notes:

This Pull Request required the creation of a new branch since it is incompatible with the previous version of Carapace, which was created using the 8.x-2.0 base.

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by dannylamb** [comment]
@Favenzio Travis is choking on a totally unrelated issue.  Let me address that and we'll get this pulled in.

**Comment by whikloj** [comment]
Restarting to see if it will pass now.

**Comment by whikloj** [comment]
@Favenzio I think you are going to need to rebase or maybe just add a small commit as this is not picking up the changes to the test harness.

**Comment by Favenzio** [comment]
I will pull in the changes to my repo and create a new pull request.

**Pull request closed without merging**
