### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by dannylamb**
**Github Issue**: https://github.com/Islandora/documentation/issues/1306

Some de-CLAWing going on here, too.

# What does this Pull Request do?

Gets rid of IRC in the composer.json.  Also changes homepage and issue queue links after de-CLAWing.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Review by whikloj — APPROVED** [review]
👍

**Comment by whikloj** [comment]
@dannylamb just noting that the new repositories in the Islandora organization (like Carapace) no longer get Travis because **Islandora** is still using `travis-ci.org` while **Islandora-CLAW** was using `travis-ci.com`.

Which means we need to migrate Islandora to `travis-ci.com` to allow continued integration testing.

**Comment by whikloj** [comment]
Also noting that I have no access in **Settings** to control the required statuses to remove the travis check and merge this.

**Comment by dannylamb** [comment]
I've updated all the 8.x repos to use travis-ci.com and left all the 7.x stuff at travis-ci.org.  Amazingly Github let me do that.

**Review by seth-shaw-unlv — APPROVED** [review]
👍

**Pull request merged**
