### PR TITLE
Changed adaptive theme to maintained fork.

### PR DESCRIPTION
**Pull request by nigelgbanks**
Use new fork of adaptive theme, allows carapace to be used with Drupal 9.

@Islandora/8-x-committers

### CODE REVIEW

**Comment by nigelgbanks** [comment]
>The program 'phpcpd' is currently not installed. To run 'phpcpd' please ask your administrator to install the package 'phpcpd'
The command "phpcpd --names *.module,*.inc,*.test,*.php $TRAVIS_BUILD_DIR" exited with 127.

Doesn't look like Travis builds are maintained, can we just turn that off to get this in?

**Comment by elizoller** [comment]
Travis is still being used for some repos, but in general i think we're shifting towards github actions.
this probably needs wider discussion though, besides base adaptive_theme not being supported anymore, i think there was interest  in using core drupal themes as a default instead of maintaining a custom islandora theme. 
probably worth discussing at a future tech call

**Comment by nigelgbanks** [comment]
Well for those whom already have sites using carapace this is an easy change that allows them to update to Drupal 9. Certainly does no harm. Supporting carapace or not going forward this will save existing users time and hassle until they can transition to the new theme when done.

**Comment by elizoller** [comment]
gotcha, makes sense to me

**Comment by elizoller** [comment]
i think the composer install is failing so its missing phpcpd https://travis-ci.com/github/Islandora/carapace/jobs/496507435#L637
i'm exploring it another PR

**Comment by elizoller** [comment]
@nigelgbanks i rolled this change into #25

**Comment by nigelgbanks** [comment]
@elizoller awesome, I'll close this.

**Pull request closed without merging**
