### PR TITLE
Updating adaptivetheme dependency

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/932

* Test with https://github.com/Islandora-Devops/claw-playbook/pull/143

# What does this Pull Request do?

Updates the dependency on adaptivetheme to get the latest code `dev-3.x`.  We were on 2.0 and need to be on 3.0.  The 3.0 dev branch has an updated conditional which solves an issue when placing blocks with context.

# What's new?
Just updated dependencies

# How should this be tested?

https://github.com/Islandora-Devops/claw-playbook/pull/143

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
@dannylamb this also needs the [mysql service](https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/.travis.yml#L6-L7) enabled on travis.

**Comment by dannylamb** [comment]
@whikloj Done

**Comment by dannylamb** [comment]
Ugh... blowing up b/c the theme is already installed.  I'll whip up a CLAW PR to get that out of the travis script.

**Comment by dannylamb** [comment]
Blowing up on something IE specific from :

`filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr='#ffffff', endColorstr='#000000');`

At the top of the file we've got: 

```
/*!
 * Hover.css (http://ianlunn.github.io/Hover/)
 * Version: 2.0.2
 * Author: Ian Lunn @IanLunn
 * Author URL: http://ianlunn.co.uk/
 * Github: https://github.com/IanLunn/Hover

 * Made available under a MIT License:
 * http://www.opensource.org/licenses/mit-license.php

 * Hover.css Copyright Ian Lunn 2014. Generated with Sass.
 */
```
Since this file is not ours and totally autogenerated, we really shouldn't be testing it with standards.  I'll dig deeper and see how much we should ignore.

**Comment by dannylamb** [comment]
It's all autogenerated...  The only thing we really should be checking is the `custom.css` file.

**Comment by dannylamb** [comment]
@whikloj Build is passing

**Review by whikloj — APPROVED** [review]
👍

**Pull request merged**
