### PR TITLE
Adding the basics

### PR DESCRIPTION
**Pull request by dannylamb**
PR template, license, contributing.md, and travis setup

### CODE REVIEW

**Comment by dannylamb** [comment]
Expecting this to explode because of coding standards

**Comment by dannylamb** [comment]
As expected, totally failing because of coding standards.  I'll go ahead and patch it up here so everything is passing, but I'm going to rebase it to keep the standards commits separate.

@Islandora-CLAW/committers when I do that, please don't squash and merge this PR.  Just do a normal merge.

**Comment by DiegoPino** [comment]
Ok. Will try to merge on my way home

**Comment by DiegoPino** [comment]
@dannylamb if you need help with ```dcs``` give me a ping.

**Comment by dannylamb** [comment]
@DiegoPino We're green thanks to `phpcbf`.  Please don't squash so the coding standards changes are isolated.

**Review by DiegoPino — APPROVED** [review]
Approving and not squashing

**Comment by DiegoPino** [comment]
@dannylamb simple merge or you prefer the rebase and merge?

**Comment by dannylamb** [comment]
@DiegoPino Simple merge will do just fine.

**Pull request merged**
