### PR TITLE
Updating to Adaptivetheme base 8.x-3.1

### PR DESCRIPTION
**Pull request by Favenzio**
# What does this Pull Request do?

This pull request updates Carapace so that it uses the latest (as of August 2018) base theme provided by Adaptivetheme (8.x-3.1)

# What's new?

Carapace has been updated so that users can make more changes to the site's look and feel using the interface provided by the theme settings. These changes include:

- Additional Menu settings available using the Responsive Menus extension tab.
- Additional fonts available using the Fonts extension tab.
- Additional Touch Icons for mobile devices available using the Touch Icons extension tab.
- Additional Shortcodes available using the Shortcodes extension tab.
- Automated creation of Flexslider Slideshows using the Slideshows extension tab.
- Additional Regions available for display and configuration using the Layouts tab.
- Additional default color schemes using the Color Scheme tab. (Known issue: Some colors are not mapping to the correct regions.)

#How should this be tested?

Make sure you have the 8.x-3.1 of Adaptivetheme (https://www.drupal.org/project/adaptivetheme) version installed in your /themes folder. Also, make sure you have installed the 8.x-3.2 version of at_tools (https://www.drupal.org/project/at_tools) in your /modules folder. Clone or download this version of Carapace to /themes/custom and enable as you would enable any other theme. More info at: http://docs.adaptivethemes.com/

#Additional Notes:

This Pull Request required the creation of a new branch since it is incompatible with the previous version of Carapace, which was created using the 8.x-2.0 base.

#Interested parties

@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
@Favenzio looks like alot of the generated code is failing the drupal sniffer you might be able to fix most of it with `phpcbf`

**Comment by Favenzio** [comment]
@whikloj I will review the errors and fix as may be necessary. Thank you for pointing me in the direction of phpcbf.

**Comment by dannylamb** [comment]
It'll be good to see how much phpcbf can take care of.  If it still pops on a ton of stuff, maybe we should reconsider how we're applying the standards.  Since it's all auto generated, maybe we should just check the spots where we're supposed to customize (e.g. the custom.css file, not neccessarily everything else).

**Comment by whikloj** [comment]
It looks like `phpcbf` can get most, but I'm not getting any of these warnings with my local `phpcs` I guess I must need to update my sniffs.

**Comment by whikloj** [comment]
Oh I got it. There are 27 once `phpcbf` is done.

**Comment by Favenzio** [comment]
@whikloj @dannylamb All the errors have been fixed. The sniffer has warnings related to minified files and that appears to make the build fail. Any thoughts?

**Comment by whikloj** [comment]
Maybe if we change the `title-styles.css` to be `title-styles-min.css` we can add an pattern to the ignore for `*-min.css`. That would cover it and `hover-min.css`.

**Comment by dannylamb** [comment]
Agreed, we need to be smarter at what we look for.  @Favenzio Is this something we'd have to deal with every 'major' update to adaptivetheme, or is this something we'd have to do every time we want to re-export and pass theme settings around?  Because the latter seems pretty inconvenient.

**Comment by Favenzio** [comment]
I think @whikloj's idea of ignoring *-min.css should work. Is that something you would be willing to consider @dannylamb ?

**Comment by dannylamb** [comment]
@Favenzio yeah totally.  I would prefer this be as painless as possible.  Thanks for jumping through all these hoops with us.

**Comment by Favenzio** [comment]
No problem @dannylamb. In the future I will run phpcs on my end prior to submitting PRs in order to avoid the majority of the hoop jumping. Thank you and @whikloj  for your patience. :)

**Comment by dannylamb** [comment]
@Favenzio I'm even keen on ignoring the code altogether if it was auto generated.  :man_shrugging:

**Comment by Favenzio** [comment]
@dannylamb I think it's something we can explore if it becomes a real issue, but my sense of it right now is that it wouldn't be very difficult to ensure generated code meets Drupal standards before committing. I would advocate for ignoring *-min.css files for now and revisiting generated code issues in the future.

**Comment by whikloj** [comment]
Run it man, run it

**Comment by dannylamb** [comment]
Thx a ton @Favenzio

**Comment by Favenzio** [comment]
Woohoo! Going on vacation until next week. When I come back I plan to create some tutorials to help users get acquainted with the possibilities behind the new branch.

**Pull request merged**
